### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by appuCoding** [GovindaBachani/cs5610fall2015#1]
Good work but call backs is not used in the assignment 3 

For example : 

function name(username, password, callback)

**Comment by GovindaBachani** [comment]
Hi Sneha,

Callbacks were supposed to be used in Services (UserService and FormService) for Assignment 3. They have been used.

https://github.com/GovindaBachani/cs5610fall2015/blob/v0.3/public/assignment/service/FormService.js

https://github.com/GovindaBachani/cs5610fall2015/blob/v0.3/public/assignment/service/UserService.js

Can you check please?
